# Generated by Django 2.2.3 on 2023-02-22 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorders',
            name='date_request',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
